apiVersion: v1
kind: Pod
metadata: 
  name: test-pod
spec: 
  serviceAccountName: my-sa
  containers:
  - name: nginx
    image: nginx:stable
    command: ['sh', '-c', 'while true; do curl -s --header "Authorization: Bearer $(cat /cert/sa-token)" --cacert /cert/sa-ca.crt https://kubernetes/api/v1/namespaces/default/pods; sleep 5; done']
    volumeMounts:
    - name: ca-cert
      mountPath: /cert
  volumes:
  - name: ca-cert
    hostPath:
      path: /home/docker/cert
      type: Directory
