apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 61Mi
        cpu: 10m
      limits:
        memory: 100Mi
        cpu: 100m
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: asdfasdf
  namespace: test
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 256Mi
    limits.cpu: "2"
    limits.memory: 512Mi
