apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  containers:
  - name: nginx
    image: nginx:stable
  initContainers:
  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'sleep 10']
    
     
